name: Compatibility tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            xcode-version: "16.4"   # Swift 6.1.2
    runs-on: ${{ matrix.os }}
    env:
      OPENRENDERBOX_WERROR: 1
      OPENRENDERBOX_RENDERBOX: 1
      OPENRENDERBOX_COMPATIBILITY_TEST: 1
      OPENRENDERBOX_USE_LOCAL_DEPS: 1
      OPENRENDERBOX_TARGET_RELEASE: 2024
      DARWIN_PRIVATE_FRAMEWORKS_TARGET_RELEASE: 2024
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: OpenSwiftUIProject/OpenSwiftUI/.github/actions/setup-xcode@main
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Set up build environment
        run: Scripts/CI/darwin_setup_build.sh
        shell: bash
      - name: Swift version
        run: swift --version
      - name: Run tests against Apple's RENDERBOX on macOS via SwiftPM
        env:
          OPENRENDERBOX_LIBRARY_EVOLUTION: 0
        run: |
          swift test \
            --build-path .build-compatibility-test-debug
      - name: Run tests against Apple's RENDERBOX on macOS via Xcode
        run: |
          xcodebuild test \
            -scheme OpenRenderBox-Package \
            -sdk macosx \
            -destination "platform=macOS" \
            -skipPackagePluginValidation \
            -skipMacroValidation