name: macOS 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_test:
    name: Execute tests on macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode-version: [16.3]   # Swift 6.1
    runs-on: ${{ matrix.os }}
    env:
      OPENBOX_WERROR: 1
      OPENBOX_RENDERBOX: 0
      OPENBOX_COMPATIBILITY_TEST: 0
      OPENBOX_USE_LOCAL_DEPS: 1
      OPENBOX_TARGET_RELEASE: 2024
      DARWIN_PRIVATE_FRAMEWORKS_TARGET_RELEASE: 2024
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Set up build environment
        run: Scripts/CI/darwin_setup_build.sh
        shell: bash
      - name: Swift version
        run: swift --version
      - name: Build and run tests in debug mode with coverage
        env:
          OPENBOX_LIBRARY_EVOLUTION: 0
        run: |
          swift test \
            -c debug \
            --enable-code-coverage \
            --build-path .build-test-debug
          xcrun llvm-cov show \
            -instr-profile=.build-test-debug/debug/codecov/default.profdata \
            .build-test-debug/debug/OPENBOXPackageTests.xctest/Contents/MacOS/OPENBOXPackageTests \
            > coverage.txt
      - name: Build and run tests in release mode
        env:
          OPENBOX_LIBRARY_EVOLUTION: 0
        run: |
          swift test \
            -c release \
            --enable-code-coverage \
            --build-path .build-test-release
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
