name: Ubuntu 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu_test:
    name: Execute tests on Ubuntu
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["6.1"]
    runs-on: ubuntu-22.04
    env:
      OPENBOX_WERROR: 1
      OPENBOX_RENDERBOX: 0
      OPENBOX_COMPATIBILITY_TEST: 0
    container: swift:${{ matrix.swift_version }}-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: |
          which swift && swift --version
      - name: Toolchain fix patch
        run: |
          # Fix swift-corelibs-foundation#5211
          .github/scripts/fix-toolchain.sh
      - name: Building and running tests in debug mode with coverage
        run: |
          swift test \
            -c debug \
            --enable-code-coverage \
            --build-path .build-test-debug
          llvm-cov show \
            -instr-profile=.build-test-debug/debug/codecov/default.profdata \
            .build-test-debug/debug/OpenBoxPackageTests.xctest \
            > coverage.txt
      - name: Building and running tests in release mode
        run: |
          swift test \
            -c release \
            --build-path .build-test-release
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
